#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import argh
from argh import arg


@arg('-t', '--term', help='terms, for example: 19', nargs='+')
def grade(**kwargs):
    '''
    获取考试成绩
    '''
    from src.grade import Grade

    username = kwargs['username']
    password = open(kwargs['password']).read().strip()

    g = Grade(username=username, password=password)

    if kwargs['term']:
        g.output(*kwargs['term'])
    else:
        g.output()


@arg('-t', '--term', help='terms, for example: 19', nargs='+', required=True)
def exam(**kwargs):
    '''
    获取考试安排
    '''
    from src.exam import Exam

    username = kwargs['username']
    password = open(kwargs['password']).read().strip()

    e = Exam(username=username, password=password)
    e.output(*kwargs['term'])


@arg('-s', '--start', help='time start, for example: 2020-9-1, today by default')
@arg('-e', '--end', help='time end, for example: 2020-12-31, today + 180 days by default')
@arg('-o', '--output', help='output classtable to the file in `ics` format')
@arg('-a', '--alarm', help='alarm before class, default: 20, set 0 to disable alarm', default=20)
def classTable(**kwargs):
    '''
    获取课表
    '''
    import os
    from QingQiz import log
    from src.classTable import ClassTable

    if kwargs['output'] and os.path.exists(kwargs['output']):
        log.yes_or_no(f'{kwargs["output"]} exists, overwrite it?')

    username = kwargs['username']
    password = open(kwargs['password']).read().strip()

    ct = ClassTable(username=username, password=password)
    ct.output(kwargs['start'], kwargs['end'], **kwargs)


if __name__ == '__main__':
    parser = argh.ArghParser()
    parser.add_argument('-u', '--username', required=True, help='username')
    parser.add_argument('-p', '--password', required=True, help='password FILE path')

    parser.add_commands([grade, exam, classTable])

    parser.dispatch()
